auto versionsasdasdaasd

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -60,7 +60,19 @@ jobs:
 
         - name: Read version from file
           id: version
-          run: echo "version=$(grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' gradle_build_output.txt | head -n 1)" >> $GITHUB_ENV
+          run: echo "version=$(grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' gradle_build_output.txt | head -n 1)" >> $GITHUB_OUTPUT
+
+        # output the version
+        - name: log the output version
+          run: echo ${{ steps.version.outputs.version }}
+        # check the version is valid
+        - name: Check version is valid
+          run: |
+            if [ -z "${{ steps.version.outputs.version }}" ]; then
+              echo "Version not found."
+              exit 1
+            fi
+        
 
         - name: Bump version and push tag
           id: tag
